- name: Download wordpress.conf
  ansible.builtin.get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp


- name: Extract wordpress into /var/lib/foo
  ansible.builtin.unarchive:
    src: /tmp/wordpress-6.7.1.tar.gz
    dest: /tmp
